[package]
name = "socks"
version = "0.0.1"
authors = ["Tomasz Miąsko <tomasz.miasko@gmail.com>"]

[dependencies]
byteorder = "0.5"
futures = "0.1"
tokio-core = "0.1"
url = { git = "https://github.com/servo/rust-url" }
